# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/modulator_ipi_source_files/modulator_ipi_rtl.xdc

# Block Designs: bd/modulator_ipi/modulator_ipi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi || ORIG_REF_NAME==modulator_ipi}]

# IP: bd/modulator_ipi/ip/modulator_ipi_frequency_trigger_0_0/modulator_ipi_frequency_trigger_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_frequency_trigger_0_0 || ORIG_REF_NAME==modulator_ipi_frequency_trigger_0_0}]

# IP: bd/modulator_ipi/ip/modulator_ipi_counter_0_0/modulator_ipi_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_counter_0_0 || ORIG_REF_NAME==modulator_ipi_counter_0_0}]

# IP: bd/modulator_ipi/ip/modulator_ipi_sine_0_0/modulator_ipi_sine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_sine_0_0 || ORIG_REF_NAME==modulator_ipi_sine_0_0}]

# IP: bd/modulator_ipi/ip/modulator_ipi_pwm_0_0/modulator_ipi_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_pwm_0_0 || ORIG_REF_NAME==modulator_ipi_pwm_0_0}]

# IP: bd/modulator_ipi/ip/modulator_ipi_xlconstant_0_0/modulator_ipi_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_xlconstant_0_0 || ORIG_REF_NAME==modulator_ipi_xlconstant_0_0}]

# IP: bd/modulator_ipi/ip/modulator_ipi_xlconstant_1_0/modulator_ipi_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_xlconstant_1_0 || ORIG_REF_NAME==modulator_ipi_xlconstant_1_0}]

# IP: bd/modulator_ipi/ip/modulator_ipi_xlconstant_2_0/modulator_ipi_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_xlconstant_2_0 || ORIG_REF_NAME==modulator_ipi_xlconstant_2_0}]

# IP: bd/modulator_ipi/ip/modulator_ipi_xlconstant_3_0/modulator_ipi_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==modulator_ipi_xlconstant_3_0 || ORIG_REF_NAME==modulator_ipi_xlconstant_3_0}]

# XDC: bd/modulator_ipi/modulator_ipi_ooc.xdc
