# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.cache/wt [current_project]
set_property parent.project_path /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/brian/0404/IP_Package/ip_repository [current_project]
set_property ip_output_repo /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/hdl/modulator_ipi_wrapper.v
add_files /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/modulator_ipi.bd
set_property used_in_implementation false [get_files -all /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/modulator_ipi_ooc.xdc]
set_property is_locked true [get_files /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/modulator_ipi.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/constrs_1/imports/modulator_ipi_source_files/modulator_ipi_rtl.xdc
set_property used_in_implementation false [get_files /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/constrs_1/imports/modulator_ipi_source_files/modulator_ipi_rtl.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top modulator_ipi_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef modulator_ipi_wrapper.dcp

catch { report_utilization -file modulator_ipi_wrapper_utilization_synth.rpt -pb modulator_ipi_wrapper_utilization_synth.pb }
