# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/brian/0404/IP_Package/modulator_ip/modulator_ip.cache/wt [current_project]
set_property parent.project_path /home/brian/0404/IP_Package/modulator_ip/modulator_ip.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/brian/0404/IP_Package/ip_repository [current_project]
set_property ip_output_repo /home/brian/0404/IP_Package/modulator_ip/modulator_ip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/frequency_trigger_ip/frequency_trigger_ip.dcp
set_property used_in_implementation false [get_files /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/frequency_trigger_ip/frequency_trigger_ip.dcp]
add_files -quiet /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip.dcp
set_property used_in_implementation false [get_files /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip.dcp]
add_files -quiet /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/sine_ip/sine_ip.dcp
set_property used_in_implementation false [get_files /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/sine_ip/sine_ip.dcp]
add_files -quiet /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/pwm_ip/pwm_ip.dcp
set_property used_in_implementation false [get_files /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/pwm_ip/pwm_ip.dcp]
read_verilog -library xil_defaultlib {
  /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/imports/modulator_source_files/modulator_ip_rtl.v
  /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/imports/modulator_source_files/modulator_ip_wrapper_rtl.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/constrs_1/imports/modulator_source_files/modulator.xdc
set_property used_in_implementation false [get_files /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/constrs_1/imports/modulator_source_files/modulator.xdc]


synth_design -top modulator_ip_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef modulator_ip_wrapper.dcp

catch { report_utilization -file modulator_ip_wrapper_utilization_synth.rpt -pb modulator_ip_wrapper_utilization_synth.pb }
