set_property SRC_FILE_INFO {cfile:/home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/constrs_1/imports/modulator_source_files/modulator.xdc rfile:../../../modulator_ip.srcs/constrs_1/imports/modulator_source_files/modulator.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T22 [get_ports pwm_out]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y9 [get_ports clk_p]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F22 [get_ports sw0]
