# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/brian/0404/IP_Package/modulator_ip/modulator_ip.cache/wt [current_project]
set_property parent.project_path /home/brian/0404/IP_Package/modulator_ip/modulator_ip.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/brian/0404/IP_Package/ip_repository [current_project]
set_property ip_output_repo /home/brian/0404/IP_Package/modulator_ip/modulator_ip.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip.xci
set_property is_locked true [get_files /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/brian/0404/IP_Package/modulator_ip/modulator_ip.runs/counter_ip_synth_1 -new_name counter_ip -ip [get_ips counter_ip]]

if { $cached_ip eq {} } {

synth_design -top counter_ip -part xc7z020clg484-1 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix counter_ip_ counter_ip.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ counter_ip_stub.v
 lappend ipCachedFiles counter_ip_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ counter_ip_stub.vhdl
 lappend ipCachedFiles counter_ip_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ counter_ip_sim_netlist.v
 lappend ipCachedFiles counter_ip_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ counter_ip_sim_netlist.vhdl
 lappend ipCachedFiles counter_ip_sim_netlist.vhdl

 config_ip_cache -add -dcp counter_ip.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips counter_ip]
}

rename_ref -prefix_all counter_ip_

write_checkpoint -force -noxdef counter_ip.dcp

catch { report_utilization -file counter_ip_utilization_synth.rpt -pb counter_ip_utilization_synth.pb }

if { [catch {
  file copy -force /home/brian/0404/IP_Package/modulator_ip/modulator_ip.runs/counter_ip_synth_1/counter_ip.dcp /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/brian/0404/IP_Package/modulator_ip/modulator_ip.runs/counter_ip_synth_1/counter_ip.dcp /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/brian/0404/IP_Package/modulator_ip/modulator_ip.runs/counter_ip_synth_1/counter_ip_stub.v /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/brian/0404/IP_Package/modulator_ip/modulator_ip.runs/counter_ip_synth_1/counter_ip_stub.vhdl /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/brian/0404/IP_Package/modulator_ip/modulator_ip.runs/counter_ip_synth_1/counter_ip_sim_netlist.v /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/brian/0404/IP_Package/modulator_ip/modulator_ip.runs/counter_ip_synth_1/counter_ip_sim_netlist.vhdl /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/brian/0404/IP_Package/modulator_ip/modulator_ip.ip_user_files/ip/counter_ip]} {
  catch { 
    file copy -force /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_stub.v /home/brian/0404/IP_Package/modulator_ip/modulator_ip.ip_user_files/ip/counter_ip
  }
}

if {[file isdir /home/brian/0404/IP_Package/modulator_ip/modulator_ip.ip_user_files/ip/counter_ip]} {
  catch { 
    file copy -force /home/brian/0404/IP_Package/modulator_ip/modulator_ip.srcs/sources_1/ip/counter_ip/counter_ip_stub.vhdl /home/brian/0404/IP_Package/modulator_ip/modulator_ip.ip_user_files/ip/counter_ip
  }
}
