# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/modulator_ipi_system_ila_0.xci
# IP: The module: 'modulator_ipi_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/bd_db1b.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_db1b || ORIG_REF_NAME==bd_db1b}]

# IP: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/ip/ip_0/bd_db1b_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_db1b_ila_lib_0 || ORIG_REF_NAME==bd_db1b_ila_lib_0}]

# XDC: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_db1b_ila_lib_0 || ORIG_REF_NAME==bd_db1b_ila_lib_0}] {/inst }]/inst ]]

# XDC: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/ip/ip_0/bd_db1b_ila_lib_0_ooc.xdc

# XDC: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/bd_db1b_ooc.xdc

# IP: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/modulator_ipi_system_ila_0.xci
# IP: The module: 'modulator_ipi_system_ila_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/bd_db1b.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_db1b || ORIG_REF_NAME==bd_db1b}]

# IP: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/ip/ip_0/bd_db1b_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_db1b_ila_lib_0 || ORIG_REF_NAME==bd_db1b_ila_lib_0}]

# XDC: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_db1b_ila_lib_0 || ORIG_REF_NAME==bd_db1b_ila_lib_0}] {/inst }]/inst ]]

# XDC: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/ip/ip_0/bd_db1b_ila_lib_0_ooc.xdc

# XDC: /home/brian/0404/IP_Integrator/modulator_ipi/modulator_ipi.srcs/sources_1/bd/modulator_ipi/ip/modulator_ipi_system_ila_0/bd_0/bd_db1b_ooc.xdc
